
'use server';

import { getFirestore, FieldPath} from 'firebase-admin/firestore';
import { getAdminApp } from '@/firebase/admin/admin';
import { revalidatePath } from 'next/cache';
import type { Product } from '@/types/product';

const db = getFirestore(getAdminApp());

interface CustomerDoc {
    id: string;
    cart: { productId: string; quantity: number; }[];
}

interface OrderPayload {
    businessId: string;
    customerId: string;
    customerName: string;
    shippingAddress: string;
    fulfillmentMethod: 'delivery' | 'pickup';
    paymentMethod: 'online' | 'on_delivery';
    transactionId?: string;
}

async function verifyFlutterwaveTransaction(transactionId: string): Promise<any> {
    const secretKey = process.env.FLUTTERWAVE_SECRET_KEY;
    if (!secretKey) {
        throw new Error("Flutterwave secret key is not configured on the server.");
    }
    
    const url = `https://api.flutterwave.com/v3/transactions/${transactionId}/verify`;

    const response = await fetch(url, {
        headers: {
            'Authorization': `Bearer ${secretKey}`
        }
    });

    if (!response.ok) {
        throw new Error(`Failed to verify transaction with Flutterwave: ${response.statusText}`);
    }

    return response.json();
}

export async function createOrder(payload: OrderPayload) {
        try {
                // --- SERVER-AUTHORITATIVE CART FETCHING ---
                        // The server, not the client, is the source of truth for the cart.
                                // This prevents the client from sending tampered data and fixes the 414 error.
                                        const customerRef = db.collection('businesses').doc(payload.businessId).collection('customers').doc(payload.customerId);
                                                const customerSnap = await customerRef.get();
                                                        if (!customerSnap.exists) {
                                                                    return { success: false, error: "Customer record not found." };
                                                                            }
                                                                                    const customerCart = (customerSnap.data() as CustomerDoc).cart || [];
                                                                                            
                                                                                                    if (customerCart.length === 0) {
                                                                                                                return { success: false, error: "Cannot create an order with an empty cart." };
                                                                                                                        }

                                                                                                                                const productIds = customerCart.map(item => item.productId);
                                                                                                                                        const productsRef = db.collection('businesses').doc(payload.businessId).collection('products');
                                                                                                                                                const productsSnap = await productsRef.where(FieldPath.documentId(), 'in', productIds).get();

                                                                                                                                                        const productDataMap = new Map<string, Product>();
                                                                                                                                                                productsSnap.forEach(doc => {
                                                                                                                                                                            productDataMap.set(doc.id, { id: doc.id, ...doc.data() } as Product);
                                                                                                                                                                                    });

                                                                                                                                                                                            // 2. Validate all products exist and build final order items with authoritative data.
                                                                                                                                                                                                    let calculatedTotal = 0;
                                                                                                                                                                                                            const finalOrderItems = customerCart.map(item => {
                                                                                                                                                                                                                        const product = productDataMap.get(item.productId);
                                                                                                                                                                                                                                    if (!product) {
                                                                                                                                                                                                                                                    throw new Error(`Product with ID ${item.productId} not found.`);
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                            const price = product.discountedPrice ?? product.price;
                                                                                                                                                                                                                                                                                        calculatedTotal += price * item.quantity;
                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                    productId: item.productId,
                                                                                                                                                                                                                                                                                                                                    title: product.title,
                                                                                                                                                                                                                                                                                                                                                    quantity: item.quantity,
                                                                                                                                                                                                                                                                                                                                                                    price: price,
                                                                                                                                                                                                                                                                                                                                                                                    imageUrls: product.imageUrls || [],
                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                // 3. Verify payment if applicable
                                                                                                                                                                                                                                                                                                                                                                                                                        if (payload.paymentMethod === 'online') {
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!payload.transactionId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { success: false, error: "Online payment requires a transaction ID." };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const verificationResponse = await verifyFlutterwaveTransaction(payload.transactionId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        verificationResponse.status !== 'success' ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        verificationResponse.data.status !== 'successful' ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        verificationResponse.data.amount < calculatedTotal || // Use server-calculated total
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        verificationResponse.data.currency !== 'UGX'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return { success: false, error: "Payment verification failed. Please contact support." };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // 4. Create the order document.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const orderRef = db.collection('businesses').doc(payload.businessId).collection('orders').doc();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const businessDoc = (await db.collection('businesses').doc(payload.businessId).get()).data();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const newOrder = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             id: orderRef.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         businessId: payload.businessId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     businessName: businessDoc?.name || '', // Add business name for TTS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 customerId: payload.customerId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             customerName: payload.customerName || (customerSnap.data() as CustomerDoc).username,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         shippingAddress: payload.fulfillmentMethod === 'delivery' ? payload.shippingAddress : '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     fulfillmentMethod: payload.fulfillmentMethod,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 paymentMethod: payload.paymentMethod,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             paymentStatus: payload.paymentMethod === 'online' ? 'paid' : 'unpaid',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         orderStatus: 'pending',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     orderDate: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 transactionId: payload.transactionId || null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             totalAmount: calculatedTotal,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         items: finalOrderItems,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         await orderRef.set(newOrder);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // 5. Clear the user's cart.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 await customerRef.update({ cart: [] });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Revalidate paths for both the customer's order history and the owner's dashboard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 revalidatePath(`/store/${payload.businessId}/orders`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         revalidatePath(`/dashboard/orders`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return { success: true, orderId: orderRef.id };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             console.error("Failed to create order:", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return { success: false, error: error.message || "An unknown error occurred during order creation." };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
}